[build]
builder = "nixpacks"
watchPatterns = ["src/**", "public/**", "package.json", "next.config.mjs"]

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
